# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "durations", :force => true do |t|
    t.column "category", :string
  end

  create_table "people", :force => true do |t|
    t.column "firstname", :string
    t.column "lastname",  :string
  end

  create_table "tasks", :force => true do |t|
    t.column "name",        :string
    t.column "duration_id", :integer
    t.column "person_id",   :integer
    t.column "updated_on",  :datetime
    t.column "created_on",  :datetime
  end

end
